name: ecommerce_dashboard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^5.0.1
  shimmer: ^3.0.0
  flutter_side_menu: ^0.5.3
  data_table_2: ^2.5.12
  lottie: ^3.3.1
  image: ^4.3.0
  image_picker: ^0.8.5+3
  flutter_dropzone: ^4.2.1
  desktop_drop: ^0.5.0
  file_picker: ^8.3.2
  hovering: ^1.0.4
  fl_chart: ^0.70.2
  flutter_thermal_printer: ^1.1.0
  animated_text_kit: ^4.2.2
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^9.0.0
  
  

  # Date picker
  datepicker_dropdown: ^0.1.6

  # Dropdown search
#  flutter_typeahead: ^5.2.0
#  searchfield: ^1.2.2
  dropdown_search: ^6.0.2

  # Date picker
  syncfusion_flutter_datepicker: ^28.1.41

  # Web Specific
  url_strategy: ^0.3.0
  universal_html: ^2.2.4

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.6

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Reports
  pdf: ^3.11.2
  printing: ^5.14.0
  path_provider: ^2.1.1
  uuid: ^4.5.1
  path: ^1.8.3


  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  cached_network_image: ^3.4.1
  js: ^0.6.5
  supabase_flutter: ^2.8.3
  vtable: ^0.4.0
  window_manager: ^0.4.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: 0.14.3


flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/logos/OMG_logo.png"
  image_path: "assets/logos/OMG_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

# flutter_native_splash configuration (root level, not under flutter)
flutter_native_splash:
  color: "#FFFFFF" # Background color of the splash screen
  image: assets/images/splash_logo.png # Path to your splash screen logo
  android: true
  ios: true
  web: true
  windows: true
  fullscreen: false # Set to true if you want a fullscreen splash screen